#!/usr/bin/env bash

set -e

CONFIG="install.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" \
	-p dotbot-plugins/dotbot-if/if.py \
	-p dotbot-plugins/dotbot-includes/includes.py \
	"${@}"

#sudo "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "packages.yaml" -p dotbot-plugins/dotbot-yum/yum.py -p dotbot-plugins/dotbot-if/if.py "${@}"
